site_name: Soundmining
site_url: https://danielstahl.github.io/soundmining-monorepo/
theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: black
  features:
    - navigation.instant
    - navigation.indexes
  logo: assets/avatar-small.jpeg
  font:
    text: Lato
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - md_in_html

plugins:
  - search
  - blog:
      blog_dir: blog
      archive: true    
      categories: true      
      archive_date_format: MMMM yyyy
  - tags
  - meta
  

repo_url: https://github.com/danielstahl/soundmining-monorepo


extra:
  social:
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/artist/1JCdKZdnXmyIKR2q9YtrHG
    - icon: fontawesome/brands/soundcloud
      link: https://soundcloud.com/danielstahl
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@soundmining7172

nav:
  - About: index.md
  - Music:
    - music/index.md
    - Birds before the storm: music/concrete-music-15.md
    - Bright Light Night: music/module-music-11.md    
  - Posts: blog/index.md
  - Tags: tags.md

not_in_nav: |
  blog/posts/*
