import subprocess
from dataclasses import dataclass
from pathlib import Path

from soundmining_library.environment import ProjectEnvironment


@dataclass
class ReaperTrack:
    name: str
    channel: int  # 0-based, matching SuperCollider NRT output channel indexing


@dataclass
class ReaperFolder:
    name: str
    tracks: list[ReaperTrack]


@dataclass
class ReaperProject:
    audio_file: Path
    folders: list[ReaperFolder]


_REAPER_SCRIPT_HEADER = """\
-- import_audio.lua
-- Auto-generated by soundmining Tools. Do not edit by hand.
 
local function create_folder(index, name)
  reaper.InsertTrackAtIndex(index, false)
  local folder = reaper.GetTrack(0, index)
  reaper.GetSetMediaTrackInfo_String(folder, 'P_NAME', name, true)
  reaper.SetMediaTrackInfo_Value(folder, 'I_FOLDERDEPTH', 1)
  reaper.SetMediaTrackInfo_Value(folder, 'I_FOLDERCOMPACT', 0)
end
 
local function import_audio(index, channel, track_name, file_name, last_in_folder)
  local folder_depth = last_in_folder and -1 or 0
  reaper.SetEditCurPos(0, false, false)
  reaper.InsertTrackAtIndex(index, false)
  local tr = reaper.GetTrack(0, index)
  reaper.GetSetMediaTrackInfo_String(tr, 'P_NAME', track_name, true)
  reaper.SetMediaTrackInfo_Value(tr, 'I_FOLDERDEPTH', folder_depth)
  reaper.SetOnlyTrackSelected(tr, true)
  reaper.InsertMedia(file_name, 0)
  local item = reaper.GetTrackMediaItem(tr, 0)
  local take = reaper.GetActiveTake(item)
  reaper.SetMediaItemTakeInfo_Value(take, 'I_CHANMODE', channel + 64 + 2)
end
 
reaper.Undo_BeginBlock()
"""

_REAPER_SCRIPT_FOOTER = """\
 
reaper.Undo_EndBlock("Import multichannel audio", -1)
reaper.UpdateArrange()
"""


class Tools:
    def __init__(self, project_environment: ProjectEnvironment) -> None:
        self._environment = project_environment

    def run_nrt_render(self, score_path: Path, output_path: Path, num_channels: int):
        sclang_path = str(self._environment.sclang_path)
        render_nrt_path = str(self._environment.render_nrt_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        command = [
            sclang_path,
            render_nrt_path,
            str(score_path),
            str(output_path),
            str(num_channels),
        ]

        result = subprocess.run(command, capture_output=True, text=True)

        print(result.stdout)

        if result.returncode != 0:
            raise RuntimeError(f"sclang exited with code {result.returncode}:\n{result.stderr}")

        if "RENDER_COMPLETE" not in result.stdout:
            raise RuntimeError(f"NRT render failed:\n{result.stdout}")

    def render_reaper_script(self, project: ReaperProject, output_path: Path | None = None) -> Path:
        """
        Render a self-contained Lua script from a ReaperProject and write it to disk.

        In Reaper: Actions -> Load ReaScript -> select the output file.
        Bind "Run last ReaScript" to a key for subsequent runs.

        Args:
            project:     The ReaperProject describing the audio file and track layout.
            output_path: Where to write the script (defaults to
                         <project score dir>/import_audio.lua).

        Returns:
            Path to the written script.
        """
        if output_path is None:
            output_path = self._environment.score_path / "import_audio.lua"

        lines = [f'local audio_file = "{project.audio_file.as_posix()}"']

        track_index = 0
        for folder in project.folders:
            lines += [
                "",
                f'create_folder({track_index}, "{folder.name}")',
            ]
            track_index += 1
            for i, track in enumerate(folder.tracks):
                last_in_folder = i == len(folder.tracks) - 1
                lines.append(f'import_audio({track_index}, {track.channel + 1}, "{track.name}", audio_file, {"true" if last_in_folder else "false"})')
                track_index += 1

        body = "\n".join(lines)
        script = _REAPER_SCRIPT_HEADER + body + _REAPER_SCRIPT_FOOTER

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script, encoding="utf-8")
        print(f"Reaper script written to: {output_path}")
        return output_path
