import subprocess
from dataclasses import dataclass
from pathlib import Path

from soundmining_library.environment import ProjectEnvironment


@dataclass
class ReaperTrack:
    name: str
    channel: int  # 0-based, matching SuperCollider NRT output channel indexing


@dataclass
class ReaperFolder:
    name: str
    tracks: list[ReaperTrack]


@dataclass
class ReaperProject:
    audio_file: Path
    folders: list[ReaperFolder]


_LUA_COMMENT = """\
-- Auto-generated by soundmining Tools. Do not edit by hand.
"""

_LUA_CREATE_FOLDER = """\
local function create_folder(index, name)
  reaper.InsertTrackAtIndex(index, false)
  local folder = reaper.GetTrack(0, index)
  reaper.GetSetMediaTrackInfo_String(folder, 'P_NAME', name, true)
  reaper.SetMediaTrackInfo_Value(folder, 'I_FOLDERDEPTH', 1)
  reaper.SetMediaTrackInfo_Value(folder, 'I_FOLDERCOMPACT', 0)
end
"""

_LUA_IMPORT_AUDIO = """\
local function import_audio(index, channel, track_name, file_name, last_in_folder)
  local folder_depth = last_in_folder and -1 or 0
  reaper.InsertTrackAtIndex(index, false)
  local tr = reaper.GetTrack(0, index)
  if not tr then return end
  reaper.GetSetMediaTrackInfo_String(tr, 'P_NAME', track_name, true)
  reaper.SetMediaTrackInfo_Value(tr, 'I_FOLDERDEPTH', folder_depth)
  reaper.SetOnlyTrackSelected(tr, true)
  reaper.SetEditCurPos(0, false, false)
  reaper.InsertMedia(file_name, 0)
  local item = reaper.GetTrackMediaItem(tr, 0)
  if not item then return end
  local take = reaper.GetActiveTake(item)
  if not take then return end
  reaper.SetMediaItemTakeInfo_Value(take, 'I_CHANMODE', channel + 64 + 2)
end
"""

_LUA_REPLACE_AUDIO = """\
local function replace_audio(index, channel, file_name)
  local tr = reaper.GetTrack(0, index)
  if not tr then return end
  for j = reaper.GetTrackNumMediaItems(tr) - 1, 0, -1 do
    local item = reaper.GetTrackMediaItem(tr, j)
    reaper.DeleteTrackMediaItem(tr, item)
  end
  reaper.SetOnlyTrackSelected(tr, true)
  reaper.SetEditCurPos(0, false, false)
  reaper.InsertMedia(file_name, 0)
  local item = reaper.GetTrackMediaItem(tr, 0)
  if not item then return end
  local take = reaper.GetActiveTake(item)
  if not take then return end
  reaper.SetMediaItemTakeInfo_Value(take, 'I_CHANMODE', channel + 64 + 2)
end
"""


def _undo_block(body: str, label: str) -> str:
    return "reaper.Undo_BeginBlock()\n\n" + body + '\nreaper.Undo_EndBlock("' + label + '", -1)\nreaper.UpdateArrange()\n'


class Tools:
    def __init__(self, project_environment: ProjectEnvironment) -> None:
        self._environment = project_environment

    def run_nrt_render(self, score_path: Path, output_path: Path, num_channels: int):
        sclang_path = str(self._environment.sclang_path)
        render_nrt_path = str(self._environment.render_nrt_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        command = [
            sclang_path,
            render_nrt_path,
            str(score_path),
            str(output_path),
            str(num_channels),
        ]

        result = subprocess.run(command, capture_output=True, text=True)

        print(result.stdout)

        if result.returncode != 0:
            raise RuntimeError(f"sclang exited with code {result.returncode}:\n{result.stderr}")

        if "RENDER_COMPLETE" not in result.stdout:
            raise RuntimeError(f"NRT render failed:\n{result.stdout}")

    def _render_script(self, script: str, output_path: Path) -> Path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(script, encoding="utf-8")
        print(f"Reaper script written to: {output_path}")
        return output_path

    def _project_lines(self, project: ReaperProject) -> tuple[str, list[str]]:
        """Return the audio_file declaration and a list of call lines for a project."""
        audio_line = f'local audio_file = "{project.audio_file.as_posix()}"'
        lines = []
        track_index = 0
        for folder in project.folders:
            lines += ["", f'create_folder({track_index}, "{folder.name}")']
            track_index += 1
            for i, track in enumerate(folder.tracks):
                last_in_folder = i == len(folder.tracks) - 1
                lines.append(f'import_audio({track_index}, {track.channel + 1}, "{track.name}", audio_file, {"true" if last_in_folder else "false"})')
                track_index += 1
        return audio_line, lines

    def render_create_script(self, project: ReaperProject, output_path: Path | None = None) -> Path:
        """
        Render a Lua script that creates the folder/track structure and imports audio.
        Run this once when setting up a new render version.

        In Reaper: Actions -> Load ReaScript -> create_tracks.lua
        """
        if output_path is None:
            output_path = self._environment.score_path / "create_tracks.lua"

        audio_line, lines = self._project_lines(project)
        body = audio_line + "\n" + "\n".join(lines)
        script = (
            "-- create_tracks.lua\n"
            + _LUA_COMMENT
            + "\n"
            + _LUA_CREATE_FOLDER
            + "\n"
            + _LUA_IMPORT_AUDIO
            + "\n"
            + _undo_block(body, "Create tracks and import audio")
        )
        return self._render_script(script, output_path)

    def render_replace_script(self, project: ReaperProject, output_path: Path | None = None) -> Path:
        """
        Render a Lua script that replaces the audio in existing tracks.
        Run this on each render iteration without touching the track structure.

        In Reaper: Actions -> Load ReaScript -> replace_audio.lua (first time),
        then bind "Run last ReaScript" to a key for subsequent runs.
        """
        if output_path is None:
            output_path = self._environment.score_path / "replace_audio.lua"

        lines = [f'local audio_file = "{project.audio_file.as_posix()}"']
        track_index = 0
        for folder in project.folders:
            track_index += 1  # skip the folder track
            for track in folder.tracks:
                lines.append(f"replace_audio({track_index}, {track.channel + 1}, audio_file)")
                track_index += 1

        body = "\n".join(lines)
        script = "-- replace_audio.lua\n" + _LUA_COMMENT + "\n" + _LUA_REPLACE_AUDIO + "\n" + _undo_block(body, "Replace audio")
        return self._render_script(script, output_path)
