name: "Dots and Strokes"
tags: 
  - musiqueconcrete
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
paths:
  artwork: "concrete-music-14"
  sounds: "concrete-music-14"
  stage: "concrete-music-14"
  score: "score"
