name: "Scream in the desert"
tags: 
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
  - musiqueconcrete
paths:
  artwork: "ambient-music-8"
  sounds: "ambient-music-8"
  stage: "ambient-music-8"
  score: "score"
