name: "Dark Humming"
tags: 
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
  - fm-synthesis
paths:
  artwork: "module-music-9"
  sounds: "module-music-9"
  stage: "module-music-9"
  score: "score"


