name: "TBD"
tags: 
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
  - granularsynthesis
paths:
  artwork: "concrete-music-16"
  sounds: "concrete-music-16"
  stage: "concrete-music-16"
  score: "score"
