name: "Heart and flow"
tags: 
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
  - musiqueconcrete
paths:
  artwork: "ambient-music-9"
  sounds: "ambient-music-9"
  stage: "ambient-music-9"
  score: "score"
