name: "Wooden clouds"
tags: 
  - musiqueconcrete
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
paths:
  artwork: "concrete-music-13"
  sounds: "concrete-music-13"
  stage: "concrete-music-13"
  score: "score"
