name: "Shadows from points"
tags: 
  - musiqueconcrete
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
paths:
  artwork: "concrete-music-12"
  sounds: "concrete-music-12"
  stage: "concrete-music-12"
  score: "score"
