name: "Bright Light Night"
tags: 
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
paths:
  artwork: "module-music-11"
  sounds: "module-music-11"
  stage: "module-music-11"
  score: "score"
