name: "Points in isolation"
tags: 
  - musiqueconcrete
  - electronicmusic
  - supercollider
  - electroacoustic
  - ambient
  - darkambient
  - generativemusic
paths:
  artwork: "concrete-music-11"
  sounds: "concrete-music-11"
  stage: "concrete-music-11"
  score: "score"
